#!/usr/bin/python2.7
from time import sleep
from hosted import device

DIR = 20
STEP = 21
CW = 1
CCW = 0
SPR = 1

# Set up the direction and step pins
device.gpio.setup_pin(DIR, "out")
device.gpio.setup_pin(STEP, "out")
device.gpio.set_pin_value(DIR, CW)

MODE = (14, 15, 18)
# Set up the resolution mode pins
for pin in MODE:
    device.gpio.setup_pin(pin, "out")

RESOLUTION = {'Full': (0, 0, 0)}
for pin, value in zip(MODE, RESOLUTION['Full']):
    device.gpio.set_pin_value(pin, value)

# Initial delay (larger value for slower start)
delay = 0.02
# Total duration of operation in seconds
total_duration = 15
# Time to increase or decrease the delay to change speed
time_to_change_delay = 0.0005
# Time to increase the delay to slow down (smaller value for more gradual slowing down)
time_to_slow_down_delay = 0.0007
# Calculate the total steps based on initial delay
total_steps = int(total_duration / (2 * delay))

for x in range(total_steps):
    device.gpio.set_pin_value(STEP, 1)
    sleep(delay)
    device.gpio.set_pin_value(STEP, 0)
    sleep(delay)
    # Speed up in the first third, slow down in the last third, constant speed in between
    if x < total_steps // 3:
        delay = max(0.005, delay - time_to_change_delay)
    elif x > 2 * total_steps // 3:
        delay += time_to_slow_down_delay
