#!/usr/bin/python2.7
from time import sleep
from hosted import device

DIR = 20
STEP = 21
CW = 1
CCW = 0
SPR = 1

# Set up the direction and step pins
device.gpio.setup_pin(DIR, "out")
device.gpio.setup_pin(STEP, "out")
device.gpio.set_pin_value(DIR, CW)

MODE = (14, 15, 18)
# Set up the resolution mode pins
for pin in MODE:
    device.gpio.setup_pin(pin, "out")

RESOLUTION = {'Full': (0, 0, 0)}
for pin, value in zip(MODE, RESOLUTION['Full']):
    device.gpio.set_pin_value(pin, value)

# Initial delay (increase this to slow down the initial speed)
delay = 0.01
# Total duration of operation in seconds
total_duration = 15
# Time to increase the delay to slow down the motor
time_to_increase_delay = 0.05
# The number of steps for the motor to take in total
total_steps = int(total_duration / (2 * delay))

for x in range(total_steps):
    device.gpio.set_pin_value(STEP, 1)
    sleep(delay)
    device.gpio.set_pin_value(STEP, 0)
    sleep(delay)
    # Increase the delay to slow down
    if x >= total_steps // 2:
        delay += time_to_increase_delay / (total_steps // 2)
